---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task

inputs:
  - name: app
    path: /app

outputs:
  - name: image

params:
  CONTEXT: /app

run:
  path: build